'use client'

import { useEffect, useState } from 'react'
import { ArrowUpRight, CalendarDays, Play, Ticket } from 'lucide-react'
import { FuturisticButton, PageShell, SectionLabel } from '@/components/site-shell'

const flyer = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/800260202_1401414058603493_4139769316431579680_n-TGbetx6Rv1sG3EQWokIkL10OgU99h2.jpeg'
const gallery = [
  ['https://hebbkx1anhila5yf.public.blob.vercel-storage.com/785362995_1034332702932523_1603632669762144956_n-Mv3jM0mq6Aiv2T5y0lrhNXHAiguXvf.jpeg','Bokomoso tables'],
  ['https://hebbkx1anhila5yf.public.blob.vercel-storage.com/793852899_1586684899571714_2844571051652538135_n-YPF408QklY14uo93oR5jkwanh6R9O4.jpeg','Arrival energy'],
  ['https://hebbkx1anhila5yf.public.blob.vercel-storage.com/799819615_1407194281348310_3414489154120803743_n-KsGZ8cYPH7cRaC8U86XkXpn7GwBhHY.jpeg','The table is set'],
  ['https://hebbkx1anhila5yf.public.blob.vercel-storage.com/789388345_2854416484957920_3250682033572926002_n-IqBW2g98f4cucb6ePq8kCSD3frmVzA.jpeg','Make an entrance'],
  ['https://hebbkx1anhila5yf.public.blob.vercel-storage.com/791361245_1088927483732929_984019893209950580_n-BSqCTUN5gzpNZqEkyVGtQ0kHt1TzPB.jpeg','The wings'],
  ['https://hebbkx1anhila5yf.public.blob.vercel-storage.com/796996539_1618333179795606_4859156682724815121_n-bRbI5u4SyJCY3OcOHt74GqU2RD5J1w.jpeg','Together at the Wall'],
]
const deadline = new Date('2026-09-19T18:00:00+02:00').getTime()
function Countdown() { const [left, setLeft] = useState(0); const [replacement, setReplacement] = useState(''); const [ready, setReady] = useState(false); useEffect(() => { const stored = window.localStorage.getItem('tgw-schedule'); if (stored) { try { setReplacement(JSON.parse(stored).replacementImage || '') } catch { setReplacement('') } } const update = () => setLeft(deadline - Date.now()); update(); setReady(true); const timer = window.setInterval(update, 1000); return () => window.clearInterval(timer) }, []); if (!ready) return <div className="countdown" aria-label="Countdown to The Wall's Finest"><span><strong>--</strong> DAYS</span><span><strong>--</strong> HRS</span><span><strong>--</strong> MIN</span><span><strong>--</strong> SEC</span></div>; if (left <= 0) return replacement ? <img className="countdown-replacement" src={replacement} alt="Scheduled event artwork" /> : <div className="countdown-expired"><span>NOW PLAYING</span><strong>THE WALL IS LIVE</strong></div>; const days = Math.floor(left / 86400000), hours = Math.floor(left / 3600000) % 24, minutes = Math.floor(left / 60000) % 60, seconds = Math.floor(left / 1000) % 60; return <div className="countdown" aria-label="Countdown to The Wall's Finest"><span><strong>{String(days).padStart(2,'0')}</strong> DAYS</span><span><strong>{String(hours).padStart(2,'0')}</strong> HRS</span><span><strong>{String(minutes).padStart(2,'0')}</strong> MIN</span><span><strong>{String(seconds).padStart(2,'0')}</strong> SEC</span></div> }
export default function HomePage() { return <PageShell><section className="home-hero event-hero"><div className="hero-flyer-bg" style={{ backgroundImage: `url(${flyer})` }} /><div className="hero-grid" /><div className="home-hero-content"><div className="live-badge"><span /> 19 SEP 2026 / GABORONE</div><h1>Where the<br /><span className="fireline"><i className="flame flame-one" /><i className="flame flame-two" /><i className="flame flame-three" /><em>future gathers.</em></span></h1><p>A creative hospitality platform for food, sound, culture and the beautifully unexpected.</p><div className="hero-actions"><FuturisticButton href="/tickets">Get tickets</FuturisticButton><a className="play-link" href="/venue"><span className="play-circle"><Play size={13} fill="currentColor" /></span> Scan the venue</a></div><div className="hero-countdown"><SectionLabel>Next transmission / 19.09.26</SectionLabel><Countdown /></div></div><a href="/tickets" className="hero-flyer-card"><img src={flyer} alt="The Wall's Finest event flyer" /><span><Ticket size={14} /> Get your P150 ticket <ArrowUpRight size={14} /></span></a></section><section className="content-section home-intro"><div><SectionLabel>00 / The frequency</SectionLabel><h2>A new kind of<br /><em>gathering place.</em></h2></div><div className="rich-copy"><p>The Great Wall is where Botswana&apos;s social energy gets amplified. A modular venue for long lunches, loud nights, deep conversations and the ideas that happen in between.</p><FuturisticButton href="/venue">Enter the venue</FuturisticButton></div></section><section className="content-section image-story"><div className="section-heading-row"><div><SectionLabel>01 / From the archive</SectionLabel><h2>Made for <em>the moment.</em></h2></div><a className="text-link" href="/gallery">View gallery <ArrowUpRight size={15} /></a></div><div className="landing-gallery">{gallery.map(([src, label], index) => <figure className={`landing-shot shot-${index + 1}`} key={src}><img src={src} alt={label} loading="lazy" /><figcaption>{label}</figcaption></figure>)}</div></section><section className="home-cta"><div><CalendarDays size={18} /><SectionLabel>02 / Reserve your frequency</SectionLabel><h2>Bring your people<br /><em>to the Wall.</em></h2></div><FuturisticButton href="/reservations">Make a reservation</FuturisticButton></section></PageShell> }
