'use client'

import { FormEvent, useState } from 'react'
import { CalendarDays, Check, Clock3, Users } from 'lucide-react'
import { PageHero, PageShell, SectionLabel } from '@/components/site-shell'
import { writeBrowserValue } from '@/lib/browser-storage'

export default function ReservationsPage() {
  const [sent, setSent] = useState(false)
  const [form, setForm] = useState({ name: '', email: '', date: '', time: '19:00', guests: '2', notes: '' })
  function submit(e: FormEvent) { e.preventDefault(); if (!form.name || !form.email || !form.date) return; setSent(true); writeBrowserValue('tgw-reservation', { ...form, createdAt: new Date().toISOString() }) }
  return <PageShell><PageHero eyebrow="Private signal / reservations" title={<>Reserve your <em>frequency.</em></>} copy="Set a table in the heart of the Great Wall. For groups larger than 12, use the contact channel and our hosts will configure a bespoke experience." /><section className="content-section reservation-section"><div className="contact-layout"><div><SectionLabel>Table protocol</SectionLabel><h2>Come for the <em>long version.</em></h2><p className="lead-copy">Dinner, sound and a little more time. Reservations are held for 15 minutes, with a two-hour standard seating window.</p><div className="reservation-details"><span><CalendarDays size={18} /><b>Wednesday — Sunday</b><small>17:00 until late</small></span><span><Clock3 size={18} /><b>Arrival window</b><small>15 minutes from selected time</small></span><span><Users size={18} /><b>Group size</b><small>2–12 guests per online request</small></span></div></div>{sent ? <div className="form-success reservation-confirmation"><Check size={22} /><strong>Request received.</strong><p>We&apos;ll confirm your table at {form.email}. Reference TGW-{form.date.replaceAll('-', '')}-01.</p><button className="button button-ghost" onClick={() => setSent(false)}>Make another request</button></div> : <form className="enquiry-form" onSubmit={submit}><SectionLabel>Request a table</SectionLabel><label>Name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Your name" /></label><label>Email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="you@example.com" /></label><div className="form-grid"><label>Date<input required type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} /></label><label>Time<select value={form.time} onChange={(e) => setForm({ ...form, time: e.target.value })}>{['17:00', '18:30', '19:00', '20:30', '21:00'].map((time) => <option key={time}>{time}</option>)}</select></label></div><label>Guests<select value={form.guests} onChange={(e) => setForm({ ...form, guests: e.target.value })}>{Array.from({ length: 11 }, (_, i) => <option key={i + 2}>{i + 2}</option>)}</select></label><label>Notes<textarea rows={4} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} placeholder="Dietary notes, celebration, access needs..." /></label><button className="button button-cyan" type="submit">Request reservation <span>↗</span></button></form>}</div></section></PageShell>
}
